# Generated by Django 4.2.30 on 2026-06-02 23:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_sessao_confirmado_em_sessao_confirmado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('humor_paciente', models.IntegerField(blank=True, null=True)),
                ('riscos_identificados', models.TextField(blank=True, null=True)),
                ('plano_terapeutico', models.TextField(blank=True)),
                ('criptografado', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='accounts.paciente')),
                ('psicologo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='accounts.psicologo')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='accounts.sessao')),
            ],
            options={
                'ordering': ['-sessao__data', '-criado_em'],
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
            },
        ),
    ]
