# Generated by Django 4.2.30 on 2026-06-30 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_historicostatussessao_options_and_more'),
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prontuario',
            options={'ordering': ['-sessao__data', '-criado_em'], 'verbose_name': 'prontuário', 'verbose_name_plural': 'prontuários'},
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='criptografado',
            field=models.BooleanField(default=True, verbose_name='criptografado'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='humor_paciente',
            field=models.IntegerField(blank=True, null=True, verbose_name='humor do paciente'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='accounts.paciente', verbose_name='paciente'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='plano_terapeutico',
            field=models.TextField(blank=True, verbose_name='plano terapêutico'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='psicologo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='accounts.psicologo', verbose_name='psicólogo'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='riscos_identificados',
            field=models.TextField(blank=True, null=True, verbose_name='riscos identificados'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='sessao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios', to='accounts.sessao', verbose_name='sessão'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='texto',
            field=models.TextField(verbose_name='texto'),
        ),
    ]
