# Generated by Django 4.2.30 on 2026-05-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_created_at_usuario_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_expiracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_recuperacao',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
