# Generated by Django 4.2.30 on 2026-05-16 18:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_codigo_expiracao_usuario_codigo_recuperacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('duracao_minutos', models.PositiveIntegerField(default=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='accounts.paciente')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='accounts.psicologo')),
            ],
            options={
                'ordering': ['-data', '-horario_inicio'],
            },
        ),
    ]
