# Generated by Django 4.2.30 on 2026-05-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sessao'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
    ]
