# Generated by Django 4.2.30 on 2026-05-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sessao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='atendido_por_plano',
            field=models.BooleanField(default=False, verbose_name='Atendido por Plano de Saúde'),
        ),
    ]
