# Generated by Django 4.2.30 on 2026-05-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sessao_atendido_por_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='isento_pagamento',
            field=models.BooleanField(default=False, verbose_name='Isento de Pagamento'),
        ),
    ]
