# Generated by Django 4.2.30 on 2026-05-19 01:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sessao_isento_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieSessao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Série de Sessões',
                'verbose_name_plural': 'Séries de Sessões',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.AddField(
            model_name='sessao',
            name='posicao_na_serie',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seriesessao',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_sessoes', to='accounts.paciente'),
        ),
        migrations.AddField(
            model_name='seriesessao',
            name='psicologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_sessoes', to='accounts.psicologo'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes', to='accounts.seriesessao'),
        ),
        migrations.AddConstraint(
            model_name='sessao',
            constraint=models.UniqueConstraint(fields=('serie', 'posicao_na_serie'), name='unique_posicao_na_serie_por_serie'),
        ),
    ]
