# Generated by Django 4.2.30 on 2026-05-20 16:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_seriesessao_sessao_posicao_na_serie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('realizada', 'Realizada'), ('falta', 'Falta')], default='pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricoStatusSessao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_anterior', models.CharField(max_length=20)),
                ('status_novo', models.CharField(max_length=20)),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='accounts.sessao')),
            ],
            options={
                'ordering': ['-alterado_em'],
            },
        ),
    ]
