# Generated by Django 4.2.30 on 2026-06-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_sessao_status_historicostatussessao"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="token_definicao_senha",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="token_definicao_senha_expira_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="token_definicao_senha_usado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
