# Generated by Django 4.2.30 on 2026-06-02 22:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usuario_token_definicao_senha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='confirmado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessao',
            name='confirmado_por',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sessao',
            name='token_confirmacao',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
