# Generated by Django 4.2.30 on 2026-06-13 19:14

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_sessao_confirmado_em_sessao_confirmado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioPensamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('situacao', django_cryptography.fields.encrypt(models.TextField(verbose_name='Situação'))),
                ('emocao_principal', models.CharField(max_length=100, verbose_name='Emoção Principal')),
                ('intensidade', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Intensidade')),
                ('observacoes_livres', django_cryptography.fields.encrypt(models.TextField(blank=True, null=True, verbose_name='Observações Livres'))),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to='accounts.paciente')),
            ],
            options={
                'verbose_name': 'Diário de Pensamento',
                'verbose_name_plural': 'Diário de Pensamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
