# Generated by Django 4.2.30 on 2026-06-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_diariopensamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariopensamento',
            name='intensidade',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Intensidade'),
        ),
    ]
