# Generated by Django 4.2.30 on 2026-06-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_diariopensamento_intensidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariopensamento',
            name='emocao_principal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emoção Principal'),
        ),
    ]
