# Generated by Django 4.2.30 on 2026-06-30 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_diariopensamento_emocao_principal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicostatussessao',
            options={'ordering': ['-alterado_em'], 'verbose_name': 'histórico de status da sessão', 'verbose_name_plural': 'históricos de status da sessão'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'paciente', 'verbose_name_plural': 'pacientes'},
        ),
        migrations.AlterModelOptions(
            name='psicologo',
            options={'verbose_name': 'psicólogo', 'verbose_name_plural': 'psicólogos'},
        ),
        migrations.AlterModelOptions(
            name='seriesessao',
            options={'ordering': ['-criada_em'], 'verbose_name': 'série de sessões', 'verbose_name_plural': 'séries de sessões'},
        ),
        migrations.AlterModelOptions(
            name='sessao',
            options={'ordering': ['-data', '-horario_inicio'], 'verbose_name': 'sessão', 'verbose_name_plural': 'sessões'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
        migrations.AlterField(
            model_name='historicostatussessao',
            name='alterado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='alterado em'),
        ),
        migrations.AlterField(
            model_name='historicostatussessao',
            name='sessao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='accounts.sessao', verbose_name='sessão'),
        ),
        migrations.AlterField(
            model_name='historicostatussessao',
            name='status_anterior',
            field=models.CharField(max_length=20, verbose_name='status anterior'),
        ),
        migrations.AlterField(
            model_name='historicostatussessao',
            name='status_novo',
            field=models.CharField(max_length=20, verbose_name='novo status'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='aceita_lembrete_email',
            field=models.BooleanField(default=True, verbose_name='aceita lembrete por e-mail'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='contato_emergencia_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nome do contato de emergência'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='contato_emergencia_telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone de emergência'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_completo',
            field=models.CharField(max_length=255, verbose_name='nome completo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='psicologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='accounts.psicologo', verbose_name='psicólogo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='crp',
            field=models.CharField(max_length=20, unique=True, verbose_name='CRP'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psicologo', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='seriesessao',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criada em'),
        ),
        migrations.AlterField(
            model_name='seriesessao',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_sessoes', to='accounts.paciente', verbose_name='paciente'),
        ),
        migrations.AlterField(
            model_name='seriesessao',
            name='psicologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_sessoes', to='accounts.psicologo', verbose_name='psicólogo'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='atendido_por_plano',
            field=models.BooleanField(default=False, verbose_name='atendido por plano de saúde'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='confirmado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='confirmado em'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='confirmado_por',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='confirmado por'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='data',
            field=models.DateField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='duracao_minutos',
            field=models.PositiveIntegerField(default=50, verbose_name='duração em minutos'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='horario_inicio',
            field=models.TimeField(verbose_name='horário de início'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='isento_pagamento',
            field=models.BooleanField(default=False, verbose_name='isento de pagamento'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='accounts.paciente', verbose_name='paciente'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='posicao_na_serie',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='posição na série'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='psicologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='accounts.psicologo', verbose_name='psicólogo'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes', to='accounts.seriesessao', verbose_name='série'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('realizada', 'Realizada'), ('falta', 'Falta')], default='pendente', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='token_confirmacao',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='token de confirmação'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo_expiracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expiração do código'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo_recuperacao',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='código de recuperação'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('psicologo', 'Psicólogo')], max_length=20, verbose_name='perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='token_definicao_senha',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='token de definição de senha'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='token_definicao_senha_expira_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expiração do token de definição de senha'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='token_definicao_senha_usado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='uso do token de definição de senha'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='nome de usuário'),
        ),
    ]
