# Generated by Django 4.2.30 on 2026-06-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_historicostatussessao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='data do pagamento'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='forma de pagamento'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20, verbose_name='status de pagamento'),
        ),
    ]
